# Documentação para a ação de implantação de aplicativos Web do Azure: https://github.com/Azure/webapps-deploy
# Mais ações do GitHub para o Azure: https://github.com/Azure/actions
# Mais informações sobre Python, GitHub Actions e Azure App Service: https://aka.ms/python-webapps-actions

nome : Construir e implantar aplicativo Python no Azure Web App - CotacaoCobertra

sobre :
  empurrar :
    galhos :
      - principal
  fluxo de trabalho_despacho :

empregos :
  construir :
    em execução : ubuntu-latest
    permissões :
      conteúdo : ler # Isso é necessário para ações/checkout

    passos :
      - usos : ações/checkout@v4

      - nome : Configurar versão do Python
        usos : ações/setup-python@v5
        com :
          versão python : ' 3.10 '

      - nome : Criar e iniciar ambiente virtual
        executar : |
          python -m venv venv
          fonte venv/bin/ativar
      
      - nome : Instalar dependências
        executar : pip install -r requirements.txt
        
      # Opcional: adicione etapas para executar testes aqui (PyTest, suítes de testes Django, etc.)

      - nome : Artefato Zip para implantação
        executar : zip release.zip ./* -r

      - nome : Carregar artefato para trabalhos de implantação
        usos : ações/upload-artefato@v4
        com :
          nome : python-app
          caminho : |
            release.zip
            !venv/
  implantar :
    em execução : ubuntu-latest
    necessidades : construir
    
    permissões :
      id-token : escrever # Isso é necessário para solicitar o JWT
      conteúdo : ler # Isso é necessário para ações/checkout

    passos :
      - nome : Baixar artefato do trabalho de construção
        usos : ações/download-artefato@v4
        com :
          nome : python-app

      - nome : Descompactar artefato para implantação
        executar : descompactar release.zip

      
      - nome : Login no Azure
        usos : azure/login@v2
        com :
          ID do cliente : ${{ secrets.AZUREAPPSERVICE_CLIENTID_76718DE78F904B6ABFF2B75528A86728 }}
          ID do locatário : ${{ secrets.AZUREAPPSERVICE_TENANTID_504991400977406A8F8F97DFF7FDD5F7 }}
          ID da assinatura : ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_82E213C2BE7645BC80346651B4846D77 }}

      - nome : ' Implantar no aplicativo Web do Azure '
        usos : azure/webapps-deploy@v3
        id : implantar no aplicativo da web
        com :
          nome do aplicativo : ' CotacaoCobertra '
          nome do slot : ' Produção '
